var fs = require('fs');
var path = require('path');
var util = require('util');

module.exports = function (profile, off) {
    return function (err) {
        if (err) { throw err; }

        fs.readFile(profile.hosts, function (err, data) {
            if (err) { throw err; }

            var clean = data.toString().split('\n').filter(original).join('\n');

            if (off) {
                fs.writeFile(profile.hosts, clean, capture(lifted));
            } else {
                var hose = clean + '\n' + Object.keys(profile.domains).map(lines).join('\n');
                fs.writeFile(profile.hosts, hose, capture(hosed));
            }
        });

        var generated = util.format('# generated by hose <%s>', profile.name);
        var rgenerated = new RegExp(generated, 'i');

        function original (line) {
            return !rgenerated.test(line);
        }

        function lines (domain) {
            return util.format('%s\t%s\t\t%s', profile.trap, domain, generated);
        }

        function capture (then) {
            return function (err) {
                if (err) { throw err; }
                then();
            };
        }

        function lifted () {
            var name = profile.name;
            var other = name !== 'default';
            var what = other ? util.format(' (%s)', name) : '';
            console.log('Hose turned off.' + what);
        }

        function hosed () {
            console.log(profile.trap === '0.0.0.0' ? 'Go get some work done.' : 'Done.');
        }
    };
};
